data:
  batch_size: 256
  num_workers: 2
  # Path to where you stored the dataset you downloaded and annotated
  path: "../data/build"
training:
  num_epochs: 10
  lr: 5.e-4
  smoothness: 0.01
  diversity: 0.001
  var: 0.
  orthogonality: 0.05
model:
  # Path to where to save the model checkpoints
  model_dir: "saved_models/ESM"
  # Path to where to store the weights of the pretrained ESM model
  weights_path: ".weights/esm2"
  name: "ESM_35M"
  attention_heads: 20
  embed_dim: 480
  num_layers: 12